# Generated by Django 6.0.1 on 2026-02-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_college_alter_department_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
