# Generated by Django 6.0.1 on 2026-02-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
