# Generated by Django 5.2.11 on 2026-02-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
