# Generated by Django 6.0.1 on 2026-01-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
