# Generated by Django 6.0.1 on 2026-01-31 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('orders', '0002_order_ordered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('bulk', 'Bulk')], default='normal', max_length=20),
        ),
    ]
