# Generated by Django 6.0.1 on 2026-02-02 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_college_alter_department_college'),
        ('orders', '0003_order_department_order_note_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.college'),
        ),
    ]
